spring:
  application:
    name: heycar-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/heycar
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


server: 
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
    metrics:
      enabled: true
      sensitive: false

